name: 'Telegram Workflow Notification'
description: 'GitHub Action for sending workflow run results to Telegram'
author: 'Daniel Pham'
branding:
  icon: bell
  color: black

inputs:
  TELEGRAM_TOKEN:
    description: 'Telegram Bot Token'
    required: true
  TELEGRAM_CHAT_ID:
    description: 'Telegram Chat ID'
    required: true
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Python environment
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install requests PyGithub

    - name: Run Notification Script
      shell: bash
      run: |
        python main.py
      env:
        TELEGRAM_TOKEN: ${{ inputs.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ inputs.TELEGRAM_CHAT_ID }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
