name: 'Telegram Workflow Notification'
description: 'GitHub Action for sending workflow run results to Telegram'
author: 'Daniel Pham'
branding:
  icon: bell
  color: black

inputs:
  TELEGRAM_TOKEN:
    description: 'Telegram Bot Token'
    required: true
  TELEGRAM_CHAT_ID:
    description: 'Telegram Chat ID'
    required: true
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
      with:
        python-version: '3.12'

    - name: Install Python dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install requests PyGithub

    - id: telegram-notification
      shell: bash
      run: |
        if [[ -d "/__w/_actions" ]]; then
          # This is a self-hosted container runner
          python ${GITHUB_ACTION_PATH}/main.py
        else
          # This is a vm runner
          python ${{ github.action_path }}/main.py
        fi
      env:
        TELEGRAM_TOKEN: ${{ inputs.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ inputs.TELEGRAM_CHAT_ID }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
